title: Java 21 OCP Flashcards
description: A Structured collection of flashcards to help you prepare for the Oracle Certified Professional (OCP) Java 21 exam.
remote_theme: just-the-docs/just-the-docs

url: https://anasss.github.io/java21docCards/

nav_enabled: true
back_to_top: true

plugins:
  - jekyll-remote-theme
